#!/usr/bin/python
# -*- coding: UTF-8 -*-
from cli.cli import parse_argv
from cli.options import option, get_config
from vanpeople.main import get_vanpeople_posts, store_locally

# cli
options = parse_argv()

# fetch posts from vanpeople
posts = get_vanpeople_posts(option('default.vanpeople.page_numbers'))

# store locally
if 'local' in options:
    store_locally(posts)
